### ISSUE TITLE
Contributors added

### ISSUE THREAD

**Issue by snehaM2210** [Webwiznitr/Project-codeddy#2]
@all-contributors please add @deb2000-sudo for infrastructure, maintenance, projectManagement and code

**Comment by deb2000-sudo** [comment]
@all-contributors please add @deb2000-sudo for infrastructure, maintenance, projectManagement and code

**Comment by deb2000-sudo** [comment]
@all-contributors please add @snehaM2210  for infrastructure, maintenance, projectManagement and code

**Comment by deb2000-sudo** [comment]
@all-contributors please add @deb2000-sudo for mentoring and doc

**Comment by deb2000-sudo** [comment]
@all-contributors please add @snehaM2210  for mentoring and doc

**Comment by snehaM2210** [comment]
@all-contributors please add @deb2000-sudo for infrastructure, maintenance, projectManagement and code
